package com.example.springcloudalipay.entity;

public class New {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new.id
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new.url
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new.title
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new.txts
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    private String txts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new.id
     *
     * @return the value of new.id
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new.id
     *
     * @param id the value for new.id
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new.url
     *
     * @return the value of new.url
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new.url
     *
     * @param url the value for new.url
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new.title
     *
     * @return the value of new.title
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new.title
     *
     * @param title the value for new.title
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new.txts
     *
     * @return the value of new.txts
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public String getTxts() {
        return txts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new.txts
     *
     * @param txts the value for new.txts
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    public void setTxts(String txts) {
        this.txts = txts == null ? null : txts.trim();
    }
}