package com.example.springcloudalipay.mapper;

import com.example.springcloudalipay.entity.New;

public interface NewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    int insert(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    int insertSelective(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    New selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    int updateByPrimaryKeySelective(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new
     *
     * @mbggenerated Mon Dec 30 14:31:06 CST 2019
     */
    int updateByPrimaryKey(New record);
}